Third Design Review for new DFW API
WPIRoboticsEngineering/DFW pull request #9
Opened 2017-03-28 18:43 UTC by madhephaestus

This update makes the button functions a flat one-liner. The comments on the competion has beed re-written. The begin function does not take a parameter since it can only be 9600.

2017-03-29 21:50 UTC, AustinShalit requested changes

2017-03-29 21:50 UTC, AustinShalit commented on DFW.cpp
> +			// fall through when a state changes
Do we want to fall through or wait for the next loop?

2017-03-29 21:50 UTC, AustinShalit commented on DFW.cpp
> +			// fall through when a state changes
Do we want to fall through or wait for the next loop?

2017-03-29 21:50 UTC, AustinShalit commented on DFW.cpp
> +				// fall through when a state changes
Do we want to fall through or wait for the next loop?

2017-03-29 21:50 UTC, AustinShalit commented on DFW.cpp
> +			//Serial.print("\r\nPacket start = ");
We should probably remove this comment

2017-03-29 21:50 UTC, AustinShalit commented on DFW.cpp
> +			if (	packet[0] == 'A' &&
Is there an extra tab on this line?

2017-03-29 21:50 UTC, AustinShalit commented on DFW.cpp
> +				 */
We should probably remove this comment.

2017-03-29 21:50 UTC, AustinShalit commented on DFW.cpp
> +	}else{
Whitespace around else

2017-03-29 21:50 UTC, AustinShalit commented on DFW.cpp
> +		}else{
Whitespace around else

2017-03-29 21:50 UTC, AustinShalit commented on DFW.cpp
> +		if(timeSinceFlash>1000){
Whitespace after `if` and before `{`

2017-03-29 21:50 UTC, AustinShalit commented on DFW.cpp
> +	//printing = false;
Remove this comment

2017-03-29 21:50 UTC, AustinShalit commented on DFW.cpp
>  //Serial.println("jrv");
We do not need this comment

2017-03-29 21:50 UTC, AustinShalit commented on DFW.cpp
>  }
Can this function just return `byteAn[0]` instead of copying it to another piece of memory?

2017-03-29 21:50 UTC, AustinShalit commented on DFW.cpp
> +	return ((byteBu[1] & 0b00000010) == 0) ;
For all of these functions:

- remove space before `;`
- remove extra parenthesis around the expression

2017-03-29 21:50 UTC, AustinShalit commented on examples/DFWRBE1001Template/DFWRBE1001Template.ino
> +#include <DFW.h> // DFW include
Is this comment needed?  Seems very obvious.

2017-03-29 21:50 UTC, AustinShalit commented on examples/DFWRBE1001Template/auto.cpp
> +void autonomous( long time,DFW & dfw) { // function definition
Is this comment needed?  Seems very obvious.

2017-03-29 21:50 UTC, AustinShalit commented on examples/DFWTank/DFWTank.ino
> +  dfw.run();// Called to update the controllers output. Do not call faster than every 15ms.
It can now be called that fast

2017-03-29 21:50 UTC, AustinShalit commented on examples/WirelessControllercodeRBE/WirelessControllercodeRBE.ino
> +
Remove extra new lines

2017-03-30 16:42 UTC, madhephaestus commented on examples/DFWTank/DFWTank.ino
> +  dfw.run();// Called to update the controllers output. Do not call faster than every 15ms.
yes it can

2017-03-31 20:11 UTC, merged